# Generated by Django 5.2.1 on 2025-05-17 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('salary_range', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField()),
                ('YoE', models.PositiveIntegerField(help_text='Years of Experience required')),
                ('type', models.CharField(choices=[('fulltime', 'Full-time'), ('contract', 'Contract'), ('internship', 'Internship'), ('freelance', 'Freelance'), ('other', 'Other')], max_length=50)),
                ('source_url', models.URLField()),
                ('scraped_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
