# Generated by Django 5.2.1 on 2025-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, max_length=30, null=True)),
                ('job_hash', models.CharField(max_length=32, unique=True)),
                ('job_title', models.CharField(max_length=255)),
                ('company_logo', models.URLField(blank=True, null=True)),
                ('company_industry', models.CharField(blank=True, max_length=255, null=True)),
                ('company_desc', models.TextField(blank=True, null=True)),
                ('company_name', models.CharField(blank=True, max_length=255, null=True)),
                ('company_employee_size', models.CharField(blank=True, max_length=100, null=True)),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('url', models.URLField(unique=True)),
                ('job_type', models.CharField(blank=True, max_length=100, null=True)),
                ('industry', models.CharField(blank=True, max_length=255, null=True)),
                ('job_description', models.TextField(blank=True, null=True)),
                ('experience_level', models.CharField(blank=True, max_length=100, null=True)),
                ('education_level', models.CharField(blank=True, max_length=100, null=True)),
                ('salary', models.CharField(blank=True, max_length=100, null=True)),
                ('skills_required', models.TextField(blank=True, null=True)),
                ('date_posted', models.TextField(blank=True, null=True)),
                ('uploaded_to_vector_db', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
