# Generated by Django 5.2.1 on 2025-05-21 06:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_jobrecommendation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='JobRecommendation',
        ),
    ]
