# Generated by Django 5.2.1 on 2025-05-23 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0003_delete_jobrecommendation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='scraped_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='salary_range',
            new_name='education_level',
        ),
        migrations.RenameField(
            model_name='job',
            old_name='company',
            new_name='job_title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='YoE',
        ),
        migrations.RemoveField(
            model_name='job',
            name='description',
        ),
        migrations.RemoveField(
            model_name='job',
            name='source_url',
        ),
        migrations.RemoveField(
            model_name='job',
            name='title',
        ),
        migrations.RemoveField(
            model_name='job',
            name='type',
        ),
        migrations.AddField(
            model_name='job',
            name='company_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='date_posted',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_level',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='job_hash',
            field=models.CharField(default='now', max_length=32, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='job',
            name='job_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='skills_required',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='job',
            name='uploaded_to_vector_db',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='job',
            name='url',
            field=models.URLField(default='https://example.com', unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='job',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
