# Generated by Django 5.2.1 on 2025-05-23 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_job_company_desc_job_company_employee_size_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='salary',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='date_posted',
            field=models.TextField(blank=True, null=True),
        ),
    ]
