# Generated by Django 5.2.1 on 2025-05-21 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='job',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='score_match',
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='apply_link',
            field=models.URLField(default='https://asdfasdf.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='company',
            field=models.CharField(default='tokopedia', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='company_desc',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='company_employee_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='company_industry',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='company_logo',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='job_description',
            field=models.TextField(default='asdfasf'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='job_id',
            field=models.CharField(default='123', max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='location',
            field=models.CharField(default='jakarta', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='match_score',
            field=models.IntegerField(default=90),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='matched_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='required_skills',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='title',
            field=models.CharField(default='software engineer', max_length=255),
            preserve_default=False,
        ),
    ]
