# Generated by Django 5.2.1 on 2025-05-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_remove_jobrecommendation_job_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecommendation',
            name='apply_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='match_score',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='jobrecommendation',
            name='title',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
