# Generated by Django 5.2.1 on 2025-05-21 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_alter_jobrecommendation_apply_link_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='cv',
        ),
    ]
