# Generated by Django 5.2.1 on 2025-05-21 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0004_remove_jobrecommendation_cv'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobrecommendation',
            name='job_id',
            field=models.CharField(max_length=100),
        ),
    ]
