# Generated by Django 5.2.1 on 2025-05-24 03:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_jobrecommendation_matched_skills'),
        ('matching', '0005_alter_jobrecommendation_job_id'),
    ]

    operations = [
    ]
