# Generated by Django 5.2.1 on 2025-05-24 11:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0007_job_category'),
        ('matching', '0006_merge_20250524_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='apply_link',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='company',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='company_desc',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='company_employee_size',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='company_industry',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='company_logo',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='job_description',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='job_id',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='location',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='match_score',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='required_skills',
        ),
        migrations.RemoveField(
            model_name='jobrecommendation',
            name='title',
        ),
        migrations.AddField(
            model_name='jobrecommendation',
            name='job',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, related_name='recommended_to', to='jobs.job'),
            preserve_default=False,
        ),
    ]
