# Generated by Django 5.2.1 on 2025-05-24 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0007_remove_jobrecommendation_apply_link_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrecommendation',
            name='reason',
            field=models.TextField(blank=True, null=True),
        ),
    ]
