<<<<<<< HEAD
# Generated by Django 5.2.1 on 2025-05-17 09:34

import django.db.models.deletion
from django.conf import settings
=======
# Generated by Django 5.2.1 on 2025-05-17 04:57

import uuid
>>>>>>> 1ed4a22 (upload-cv)
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
<<<<<<< HEAD
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
=======
>>>>>>> 1ed4a22 (upload-cv)
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
<<<<<<< HEAD
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('file_url', models.URLField()),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cvs', to=settings.AUTH_USER_MODEL)),
=======
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(max_length=255)),
                ('file_url', models.CharField(max_length=255)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=10)),
                ('skills', models.JSONField(blank=True, null=True)),
                ('education', models.JSONField(blank=True, null=True)),
                ('experience', models.JSONField(blank=True, null=True)),
>>>>>>> 1ed4a22 (upload-cv)
            ],
        ),
    ]
