# Generated by Django 5.2.1 on 2025-05-25 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CV',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, unique=True)),
                ('file_url', models.CharField(max_length=255)),
                ('parsed_text', models.TextField(blank=True, null=True)),
                ('category', models.CharField(choices=[('teknologi', 'Teknologi'), ('bisnis_manajemen', 'Bisnis dan Manajemen'), ('kreatif', 'Kreatif'), ('industri_manufaktur', 'Industri dan Manufaktur')], default='uncategorized', max_length=50)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
        ),
    ]
