# Generated by Django 5.2.1 on 2025-05-21 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='user',
        ),
        migrations.AddField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='cv',
            name='user_id',
            field=models.CharField(default='ismail', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='cv',
            name='file_url',
            field=models.CharField(max_length=255),
        ),
    ]
