# Generated by Django 5.2.1 on 2025-05-19 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_alter_cv_education_alter_cv_experience_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='education',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='skills',
        ),
        migrations.RemoveField(
            model_name='cv',
            name='status',
        ),
    ]
