# Generated by Django 5.2.1 on 2025-05-22 00:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0002_remove_cv_user_cv_status_cv_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
