# Generated by Django 5.2.1 on 2025-05-24 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='category',
            field=models.CharField(choices=[('teknologi', 'Teknologi'), ('bisnis_manajemen', 'Bisnis dan Manajemen'), ('kreatif', 'Kreatif'), ('industri_manufaktur', 'Industri dan Manufaktur'), ('uncategorized', 'Uncategorized')], default='uncategorized', max_length=50),
        ),
    ]
