# Generated by Django 5.2.1 on 2025-05-24 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_alter_cv_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='category',
            field=models.CharField(choices=[('teknologi', 'Teknologi'), ('bisnis_manajemen', 'Bisnis dan Manajemen'), ('kreatif', 'Kreatif'), ('industri_manufaktur', 'Industri dan Manufaktur')], default='uncategorized', max_length=50),
        ),
        migrations.AlterField(
            model_name='cv',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
