# Generated by Django 5.2.1 on 2025-05-19 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0003_remove_cv_education_remove_cv_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cv',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
