# Generated by Django 5.2.1 on 2025-05-24 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cv',
            name='user_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
