# Generated by Django 5.2.1 on 2025-05-20 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cv',
            name='status',
        ),
    ]
