# Generated by Django 5.2.1 on 2025-05-24 21:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cv', '0004_cv_category_alter_cv_user_id'),
        ('cv', '0005_alter_cv_user_id'),
    ]

    operations = [
    ]
